# Config File for Global 1.1
# Before using the plugin, you'd better go through this file and change every option to what you want.

# World
# Settings about breaking blocks
NoBreak: true
BreakPermission: ori.build  # Permission Node to ignore the break limit

# Settings about placing blocks
NoPlace: true
PlacePermission: ori.build  # Permission Node to ignore the break limit

# Settings about weather
NoWeatherChange: true

# Player
# Day and Night Command
DayAndNightToggle: true

# Settings about hunger
NoHunger: true

# Settings about damage
NoDamage: true
# If you don't want to use this function below, just clear all the things below the item title,
# or you are expected to look for a totally correct DamageCause to add. (They can be from https://bukkit.windit.net/javadoc/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html)
ExceptionDamageCause:
  - SUFFOCATION
  - CUSTOM

# Settings about drop
NoDrop: true
DropPermission: ori.drop  # Permission Node to ignore the drop limit

# Settings about interaction with blocks
NoInteractionWithBlocks: true
InteractPermission: ori.build  # Permission Node to ignore the interaction limit


